spring.application.name=openlms
spring.datasource.url=jdbc:mysql://localhost:3306/openlms
spring.datasource.username=root
spring.datasource.password=Mayank@dns78
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=

server.port=8081
